name: Damn Larper - sampctl test build
on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
     
      - uses: AGraber/sampctl-action@v1
        with:
          version: '1.11.0'
       
      - run: sampctl package build --forceEnsure
      - run: sampctl version

      - uses: actions/upload-artifact@v3
        with:
          name: DamnLarper_AMX_PreRelease
          retention-days: 12 
          if-no-files-found: error
          
          path: entry/main.amx
